### ISSUE TITLE
no visible @interface for 'SocketRocketUtility' declares the selector 'SRWebSocketOpen'

### ISSUE THREAD

**Issue by miniLV** [sunsunsunJunn/SJWebSocketDemo#4]
####SocketRocketUtility.m 
//        [self SRWebSocketOpen]; 125行
替换  · [self SRWebSocketOpenWithURLString:@"ws://121.43.38.179:7397"];

- 如果有自己的服务器地址，用它替换作者demo中的 @"ws://121.43.38.179:7397"

**Comment by sunsunsunJunn** [comment]
谢谢 已经修改
